included: # paths to include during linting. `--path` is ignored if present.
- csenseTests
line_length: 150

file_length:
    warning: 500
    error: 1200

variable_name:
    min_length: 2            # only min_length

disabled_rules:

